#!/usr/bin/bash

night_mode() {
    xrandr --output eDP-1 --gamma $1 --brightness $2
    xrandr --output HDMI-2 --gamma $1 --brightness $2
}
case $1 in
  off) night_mode 1:1:1 1.0 ;;
  *) night_mode 1:0.85:0.6 1.0 ;;
esac

